version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    hostname: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  activemq:
    image: rmohr/activemq
    hostname: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    networks:
      - elk

  algorithms:
    image: algorithms
    ports:
      - "8881:8881"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: --spring.profiles.active=dev
    volumes:
      - type: bind
        source: ./execution/application-dev.yml
        target: /app/resources/application-dev.yml
        read_only: false
      - type: bind
        source: ./execution/logback-spring.xml
        target: /app/resources/logback-spring.xml
        read_only: false
    networks:
      - elk

  analytics:
    image: analytics
    ports:
      - "8882:8882"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: --spring.profiles.active=dev
    volumes:
      - type: bind
        source: ./analytics/application-dev.yml
        target: /app/resources/application-dev.yml
        read_only: false
      - type: bind
        source: ./analytics/logback-spring.xml
        target: /app/resources/logback-spring.xml
        read_only: false
    networks:
      - elk


networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
